var t = {
	"id" : [ 4, 8, 0, "", "id", "ID", 0 ],
	"uin" : [ 4, 10, 0, "用户id", "uin", "UIN", 1 ],
	"pid" : [ 4, 10, 0, "", "pid", "PID", 2 ],
	"name" : [ 12, 60, 0, "登陆名", "name", "NAME", 3 ],
	"alias" : [ 12, 60, 0, "", "alias", "ALIAS", 4 ],
	"sex" : [ 1, 1, 0, "性别", "sex", "SEX", 5 ],
	"pos" : [ 12, 30, 0, "", "pos", "POS", 6 ],
	"tel" : [ 12, 20, 0, "座机", "tel", "TEL", 7 ],
	"birth" : [ 12, 30, 0, "生日", "birth", "BIRTH", 8 ],
	"slave_alias" : [ 12, 30, 0, "", "slave_alias", "SLAVE_ALIAS", 9 ],
	"department" : [ 12, 60, 0, "部门", "department", "DEPARTMENT", 10 ],
	"mobile" : [ 12, 20, 0, "手机号", "mobile", "MOBILE", 11 ],
	"employee_no" : [ 1, 4, 0, "员工编号", "employee_no", "EMPLOYEE_NO", 12 ],
	"employee_cardno" : [ 1, 4, 0, "员工工牌号", "employee_cardno",
			"EMPLOYEE_CARDNO", 13 ],
	"employee_idcard" : [ 12, 20, 0, "身份证号码", "employee_idcard",
			"EMPLOYEE_IDCARD", 14 ],
	"logname" : [ 12, 30, 0, "登陆名", "logname", "LOGNAME", 15 ]
}
